image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install morgan
    command: npm i -save morgan
  - name: Install nodemon 
    command: npm i -g nodemon && npm start